name: Molecule Test
on: [push]
    
jobs:

  lint:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v2
        with:
          path: 'darsh12.new-role'
          
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip3 install "molecule[docker]" yamllint ansible-lint ansible docker

      - name: Run Molecule Test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
