name: Molecule Test
on: [push]

defaults:
  run:
    working-directory: 'darsh12.new-role'
    
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v2
        with:
          path: 'darsh12.new-role'
          
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip3 install yamllint
        
      - name: Frenck's yamllint
        uses: frenck/action-yamllint@v1.1.1
        with:
         config: .yamllint
